// ============================================================================
// BLAS Canada Day Trivia, GAME CONFIG
// This file encodes the locked design spec as data. The engine is driven by it.
// NOTE: Question CONTENT below is DRAFT and must be completed + fact-checked in
// the content pass. The STRUCTURE and SCORING are final.
// ============================================================================

export const AVATARS = ['moose', 'beaver', 'bear', 'loon', 'mountie', 'cntower']
export const TEAM_COLORS = ['#D80621', '#0B5394', '#128A6B', '#B8860B', '#7A3E9D', '#C2410C']

// Round TYPES: 'mc' | 'select-all' | 'clue-drip' | 'tf-rapid' | 'mixed' | 'wager'
export const ROUNDS = [
  // 1 ─────────────────────────────────────────────────────────────────────
  {
    id: 'maps',
    title: 'Which Province or Territory Is This?',
    type: 'mc',
    timerSec: 15,
    scoring: { correct: 1, wrong: -1 },
    rules: 'A map shape appears. Pick the province or territory it shows. Failure to select an answer will count as a WRONG answer.',
    pointsLabel: '+1 correct · -1 wrong or no answer',
    questions: [
      { id: 'm1', image: 'maps/bc.png', prompt: 'Which one is this?',
        options: [{ id: 'bc', label: 'British Columbia' }, { id: 'ab', label: 'Alberta' }, { id: 'ko', label: 'Kootenay' }, { id: 'ca', label: 'Cariboo' }],
        correct: 'bc', reveal: { answerName: 'British Columbia', flag: 'reveals/bc.png', blurb: `British Columbia, Canada's Pacific coast, and the 6th province to join Confederation, in 1871. Kootenay and Cariboo are real regions inside BC, but neither was ever its own province.` } },
      { id: 'm2', image: 'maps/yt.png', prompt: 'Which one is this?',
        options: [{ id: 'yt', label: 'Yukon' }, { id: 'nwt', label: 'Northwest Territories' }, { id: 'mk', label: 'Mackenzie' }, { id: 'kw', label: 'Keewatin' }],
        correct: 'yt', reveal: { answerName: 'Yukon', flag: 'reveals/yt.png', blurb: `Yukon is a territory, not a province, capital Whitehorse, and the heart of the 1890s Klondike Gold Rush. Mackenzie and Keewatin were real northern districts that never became provinces.` } },
      { id: 'm3', image: 'maps/sk.png', prompt: 'Which one is this?',
        options: [{ id: 'sk', label: 'Saskatchewan' }, { id: 'mb', label: 'Manitoba' }, { id: 'ab', label: 'Alberta' }, { id: 'as', label: 'Assiniboia' }],
        correct: 'sk', reveal: { answerName: 'Saskatchewan', flag: 'reveals/sk.png', blurb: `Saskatchewan, the prairie near-rectangle. Before it became a province in 1905, part of this land was the District of Assiniboia.` } },
      { id: 'm4', image: 'maps/on.png', prompt: 'Which one is this?',
        options: [{ id: 'on', label: 'Ontario' }, { id: 'qc', label: 'Quebec' }, { id: 'al', label: 'Algoma' }, { id: 'ni', label: 'Nipissing' }],
        correct: 'on', reveal: { answerName: 'Ontario', flag: 'reveals/on.png', blurb: `Ontario is Canada's most populous province, and that notch along the bottom is the Great Lakes. Algoma and Nipissing are real Ontario districts, not provinces.` } },
      { id: 'm5', image: 'maps/qc.png', prompt: 'Which one is this?',
        options: [{ id: 'qc', label: 'Quebec' }, { id: 'on', label: 'Ontario' }, { id: 'un', label: 'Ungava' }, { id: 'sg', label: 'Saguenay' }],
        correct: 'qc', reveal: { answerName: 'Quebec', flag: 'reveals/qc.png', blurb: `Quebec is Canada's largest province by area, La Belle Province. Ungava and Saguenay are real regions within it, but were never provinces of their own.` } },
      { id: 'm6', image: 'maps/ns.png', prompt: 'Which one is this?',
        options: [{ id: 'ns', label: 'Nova Scotia' }, { id: 'nb', label: 'New Brunswick' }, { id: 'cb', label: 'Cape Breton' }, { id: 'ac', label: 'Acadia' }],
        correct: 'ns', reveal: { answerName: 'Nova Scotia', flag: 'reveals/ns.png', blurb: `Nova Scotia is Latin for New Scotland, a peninsula plus Cape Breton Island. Cape Breton was once its own colony, and Acadia was the historic French region here.` } },
      { id: 'm7', image: 'maps/pe.png', prompt: 'Which one is this?',
        options: [{ id: 'pe', label: 'Prince Edward Island' }, { id: 'nf', label: 'Newfoundland' }, { id: 'cb', label: 'Cape Breton' }, { id: 'sj', label: 'Île Saint-Jean' }],
        correct: 'pe', reveal: { answerName: 'Prince Edward Island', flag: 'reveals/pe.png', blurb: `Prince Edward Island is Canada's smallest province. Its old French name was literally Île Saint-Jean, the exact trap in the options.` } },
      { id: 'm8', image: 'maps/nl.png', prompt: 'Which one is this?',
        options: [{ id: 'nl', label: 'Newfoundland & Labrador' }, { id: 'ns', label: 'Nova Scotia' }, { id: 'lb', label: 'Labrador' }, { id: 'av', label: 'Avalon' }],
        correct: 'nl', reveal: { answerName: 'Newfoundland & Labrador', flag: 'reveals/nl.png', blurb: `Newfoundland & Labrador was the last to join Confederation, in 1949. Labrador is only half its name, and Avalon is its southeastern peninsula.` } },
    ],
  },
  // 2 ─────────────────────────────────────────────────────────────────────
  {
    id: 'capitals',
    title: 'Provincial & Territorial Capitals',
    type: 'mc',
    timerSec: 15,
    scoring: { correct: 1, wrong: -1 },
    rules: 'A province or territory appears. Pick its capital city. Failure to select an answer will count as a WRONG answer.',
    pointsLabel: '+1 correct · -1 wrong or no answer',
    questions: [
      { id: 'c1', prompt: 'What is the capital of Alberta?',
        options: [{ id: 'ed', label: 'Edmonton' }, { id: 'ca', label: 'Calgary' }, { id: 'rd', label: 'Red Deer' }, { id: 'le', label: 'Lethbridge' }],
        correct: 'ed', reveal: { answerName: 'Edmonton', blurb: `Alberta's capital, home to West Edmonton Mall, once the world's largest. Calgary is bigger, but Edmonton holds the legislature.` } },
      { id: 'c2', prompt: 'What is the capital of British Columbia?',
        options: [{ id: 'vi', label: 'Victoria' }, { id: 'va', label: 'Vancouver' }, { id: 'ke', label: 'Kelowna' }, { id: 'su', label: 'Surrey' }],
        correct: 'vi', reveal: { answerName: 'Victoria', blurb: `On the southern tip of Vancouver Island, not in the city of Vancouver.` } },
      { id: 'c3', prompt: 'What is the capital of Saskatchewan?',
        options: [{ id: 're', label: 'Regina' }, { id: 'sa', label: 'Saskatoon' }, { id: 'pa', label: 'Prince Albert' }, { id: 'mj', label: 'Moose Jaw' }],
        correct: 're', reveal: { answerName: 'Regina', blurb: `Saskatoon is the bigger city, but Regina is the capital.` } },
      { id: 'c4', prompt: 'What is the capital of Quebec?',
        options: [{ id: 'qc', label: 'Quebec City' }, { id: 'mo', label: 'Montreal' }, { id: 'la', label: 'Laval' }, { id: 'ga', label: 'Gatineau' }],
        correct: 'qc', reveal: { answerName: 'Quebec City', blurb: `Founded in 1608, one of North America's oldest cities. Montreal is bigger but is not the capital.` } },
      { id: 'c5', prompt: 'What is the capital of New Brunswick?',
        options: [{ id: 'fr', label: 'Fredericton' }, { id: 'mn', label: 'Moncton' }, { id: 'sj', label: 'Saint John' }, { id: 'di', label: 'Dieppe' }],
        correct: 'fr', reveal: { answerName: 'Fredericton', blurb: `The sneaky one. Fredericton is smaller than both Moncton and Saint John.` } },
      { id: 'c6', prompt: 'What is the capital of Ontario?',
        options: [{ id: 'to', label: 'Toronto' }, { id: 'ot', label: 'Ottawa' }, { id: 'ha', label: 'Hamilton' }, { id: 'mi', label: 'Mississauga' }],
        correct: 'to', reveal: { answerName: 'Toronto', blurb: `The gotcha. Toronto is Ontario's capital. Ottawa is Canada's national capital, which is a different thing.` } },
      { id: 'c7', prompt: 'What is the capital of Nova Scotia?',
        options: [{ id: 'hx', label: 'Halifax' }, { id: 'sy', label: 'Sydney' }, { id: 'da', label: 'Dartmouth' }, { id: 'tr', label: 'Truro' }],
        correct: 'hx', reveal: { answerName: 'Halifax', blurb: `Nova Scotia's capital, built around one of the world's largest natural harbours.` } },
      { id: 'c8', prompt: 'What is the capital of Nunavut?',
        options: [{ id: 'iq', label: 'Iqaluit' }, { id: 'ri', label: 'Rankin Inlet' }, { id: 'cb', label: 'Cambridge Bay' }, { id: 'ar', label: 'Arviat' }],
        correct: 'iq', reveal: { answerName: 'Iqaluit', blurb: `On Baffin Island, capital of Nunavut, which is Canada's newest territory, created in 1999.` } },
    ],
  },
  // 3 ─────────────────────────────────────────────────────────────────────
  {
    id: 'spot',
    title: 'Spot the Canadian',
    type: 'select-all',
    timerSec: 30,
    scoring: { perCorrect: 1, perWrong: -1, mustPickOne: true },
    rules: 'Four faces appear. Select everyone who is Canadian. You must select at least one.',
    pointsLabel: '+1 per correct pick · -1 per wrong pick',
    questions: [
      // Photos supplied by Ayaz. isCanadian marks the correct picks.
      { id: 's1', prompt: 'Who here is Canadian?',
        options: [
          { id: 'a', label: 'TBD', img: 'people/s1a.jpg', isCanadian: true },
          { id: 'b', label: 'TBD', img: 'people/s1b.jpg', isCanadian: false },
          { id: 'c', label: 'TBD', img: 'people/s1c.jpg', isCanadian: true },
          { id: 'd', label: 'TBD', img: 'people/s1d.jpg', isCanadian: false },
        ], reveal: { blurb: '' } },
    ],
  },
  // 4 ─────────────────────────────────────────────────────────────────────
  {
    id: 'slang',
    title: 'Canadian Slang',
    type: 'mc',
    timerSec: 15,
    scoring: { correct: 1, wrong: -1 },
    rules: 'A Canadian slang word or phrase appears. Pick what it actually means. Failure to select an answer will count as a WRONG answer.',
    pointsLabel: '+1 correct · -1 wrong or no answer',
    questions: [
      { id: 'sl1', prompt: 'What is a "toque"?',
        options: [{ id: 'hat', label: 'A knitted winter hat' }, { id: 'canoe', label: 'A small canoe' }, { id: 'mitt', label: 'A type of mitten' }, { id: 'shovel', label: 'A snow shovel' }],
        correct: 'hat', reveal: { blurb: `A warm knitted winter hat. The spelling toque is distinctly Canadian, from Canadian French.` } },
      { id: 'sl2', prompt: 'What is a "double-double"?',
        options: [{ id: 'coffee', label: 'A coffee order' }, { id: 'bball', label: 'A basketball stat line' }, { id: 'burger', label: 'A double cheeseburger' }, { id: 'weekend', label: 'A long weekend' }],
        correct: 'coffee', reveal: { blurb: `A coffee with two creams and two sugars, popularized by Tim Hortons and now in the Canadian Oxford Dictionary. In basketball a double-double means something else entirely.` } },
      { id: 'sl3', prompt: 'What is a "loonie"?',
        options: [{ id: 'coin', label: 'The one-dollar coin' }, { id: 'pen', label: 'A hockey penalty' }, { id: 'boat', label: 'A small fishing boat' }, { id: 'bird', label: 'A prairie bird call' }],
        correct: 'coin', reveal: { blurb: `The one-dollar coin, named for the loon on its face. The two-dollar coin is the toonie.` } },
      { id: 'sl4', prompt: 'What is a "two-four"?',
        options: [{ id: 'case', label: 'A case of 24 beers' }, { id: 'shift', label: 'A double shift at work' }, { id: 'score', label: 'A hockey final score' }, { id: 'vac', label: 'A two-week vacation' }],
        correct: 'case', reveal: { blurb: `A case of 24 beers. The May long weekend is even nicknamed the May two-four.` } },
      { id: 'sl5', prompt: 'What is "hydro"?',
        options: [{ id: 'elec', label: 'The electricity bill' }, { id: 'spring', label: 'Bottled spring water' }, { id: 'wbill', label: 'The water bill' }, { id: 'tub', label: 'A hot tub' }],
        correct: 'elec', reveal: { blurb: `Your electricity bill. Because so much Canadian power is hydroelectric, people say things like I paid the hydro. The water-sounding options are the trap.` } },
      { id: 'sl6', prompt: 'What is a "klick"?',
        options: [{ id: 'km', label: 'A kilometre' }, { id: 'remote', label: 'A TV remote' }, { id: 'photo', label: 'A quick photo' }, { id: 'arg', label: 'A minor argument' }],
        correct: 'km', reveal: { blurb: `One kilometre. Common in Canadian and military speech, as in he lives ten klicks away.` } },
      { id: 'sl7', prompt: 'What is "The Six"?',
        options: [{ id: 'to', label: 'Toronto' }, { id: 'nhl', label: `Hockey's Original Six teams` }, { id: 'mtl', label: 'Montreal' }, { id: 'beer', label: 'A six-pack of beer' }],
        correct: 'to', reveal: { blurb: `A nickname for Toronto, made famous by Drake, from the city's six amalgamated boroughs and the 416 area code. Not to be confused with hockey's Original Six.` } },
      { id: 'sl8', prompt: 'What is a "mickey"?',
        options: [{ id: 'liquor', label: 'A small bottle of liquor' }, { id: 'nap', label: 'A quick afternoon nap' }, { id: 'remote', label: 'A TV remote control' }, { id: 'prank', label: 'A harmless prank' }],
        correct: 'liquor', reveal: { blurb: `A small 375 mL bottle of liquor, sized to slip into a pocket.` } },
    ],
  },
  // 5 ─────────────────────────────────────────────────────────────────────
  {
    id: 'city',
    title: 'Name This Canadian City',
    type: 'clue-drip',
    timerSec: 30,
    clueIntervalSec: 10,
    scoring: { tiers: [3, 2, 1], wrong: -1, mustAnswer: true },
    rules: 'Clues appear one at a time. Lock in early for more points: after clue 1 = +3, clue 2 = +2, clue 3 = +1. Your pick is FINAL, no changing it. Failure to select an answer will count as a WRONG answer.',
    pointsLabel: '+3 / +2 / +1 by clue · -1 wrong or no answer',
    questions: [
      { id: `ct1`,
        clues: [`Hosted the 1988 Winter Olympics.`, `Nicknamed "Cowtown" for its ranching and rodeo roots.`, `The ______ Stampede, the Greatest Outdoor Show on Earth. Yee-haw!`],
        options: [{ id: `cal`, label: `Calgary` }, { id: `edm`, label: `Edmonton` }, { id: `win`, label: `Winnipeg` }, { id: `reg`, label: `Regina` }],
        correct: `cal`, reveal: { blurb: `Calgary, home of the Calgary Stampede.` } },
      { id: `ct2`,
        clues: [`Its downtown sits on the shore of Lake Ontario.`, `Home to the NHL's Maple Leafs.`, `Home to the CN Tower.`],
        options: [{ id: `tor`, label: `Toronto` }, { id: `ott`, label: `Ottawa` }, { id: `ham`, label: `Hamilton` }, { id: `mis`, label: `Mississauga` }],
        correct: `tor`, reveal: { blurb: `Toronto, Canada's largest city, home to the CN Tower.` } },
      { id: `ct3`,
        clues: [`A west-coast city ringed by mountains and the Pacific.`, `Hosted the 2010 Winter Olympics.`, `Home to Stanley Park.`],
        options: [{ id: `van`, label: `Vancouver` }, { id: `vic`, label: `Victoria` }, { id: `kel`, label: `Kelowna` }, { id: `nan`, label: `Nanaimo` }],
        correct: `van`, reveal: { blurb: `Vancouver, on Canada's Pacific coast.` } },
      { id: `ct4`,
        clues: [`Its landmarks include Mount Royal.`, `The largest French-speaking city in North America.`, `Home of McGill University.`],
        options: [{ id: `mtl`, label: `Montreal` }, { id: `que`, label: `Quebec City` }, { id: `ott`, label: `Ottawa` }, { id: `lav`, label: `Laval` }],
        correct: `mtl`, reveal: { blurb: `Montreal, the largest French-speaking city in North America.` } },
      { id: `ct5`,
        clues: [`It sits at the heart of Canada's oil sands, the largest in the world.`, `It lies along the Athabasca River in far northern Alberta.`, `A massive wildfire forced its evacuation in 2016.`],
        options: [{ id: `ftm`, label: `Fort McMurray` }, { id: `grp`, label: `Grande Prairie` }, { id: `llo`, label: `Lloydminster` }, { id: `red`, label: `Red Deer` }],
        correct: `ftm`, reveal: { blurb: `Fort McMurray, the hub of Alberta's oil sands.` } },
      { id: `ct6`,
        clues: [`It sits on a river that forms a provincial border.`, `Home to Parliament Hill.`, `Canada's national capital.`],
        options: [{ id: `ott`, label: `Ottawa` }, { id: `tor`, label: `Toronto` }, { id: `gat`, label: `Gatineau` }, { id: `kin`, label: `Kingston` }],
        correct: `ott`, reveal: { blurb: `Ottawa, Canada's capital, on the Ottawa River.` } },
    ],
  },
  // 6 ─────────────────────────────────────────────────────────────────────
  {
    id: 'canadianornot',
    title: 'Canadian or Not?',
    type: 'tf-rapid',
    timerSec: 7,
    scoring: { correct: 1, wrong: -1 },
    rules: 'Rapid fire! TRUE or FALSE: is it really Canadian? 7 seconds each, no reveals until the end. Failure to select an answer will count as a WRONG answer.',
    pointsLabel: '+1 correct · -1 wrong or no answer',
    questions: [
      { id: `co1`, statement: `Nutella was invented in Canada.`, correct: false, blurb: `FALSE. Nutella is Italian, made by Ferrero.` },
      { id: `co2`, statement: `Spotify is a Canadian company.`, correct: false, blurb: `FALSE. Spotify is Swedish, from Stockholm.` },
      { id: `co3`, statement: `Basketball was invented by a Canadian.`, correct: true, blurb: `TRUE. James Naismith of Almonte, Ontario invented it in 1891.` },
      { id: `co4`, statement: `Insulin was discovered in Canada.`, correct: true, blurb: `TRUE. It was discovered at the University of Toronto in 1921.` },
      { id: `co5`, statement: `The Rubik's Cube was invented in Canada.`, correct: false, blurb: `FALSE. It was invented by Erno Rubik of Hungary.` },
      { id: `co6`, statement: `Lululemon was founded in Canada.`, correct: true, blurb: `TRUE. It started in Vancouver in 1998.` },
      { id: `co7`, statement: `Velcro was invented in Canada.`, correct: false, blurb: `FALSE. Velcro was invented by a Swiss engineer, George de Mestral.` },
      { id: `co8`, statement: `LEGO was invented in Canada.`, correct: false, blurb: `FALSE. LEGO is Danish, from Billund, Denmark.` },
      { id: `co9`, statement: `The snowmobile was invented by a Canadian.`, correct: true, blurb: `TRUE. Joseph-Armand Bombardier of Quebec invented it.` },
      { id: `co10`, statement: `Shopify is a Canadian company.`, correct: true, blurb: `TRUE. Shopify is based in Ottawa, founded in 2006.` },
      { id: `co11`, statement: `Microsoft's co-founder was Canadian.`, correct: false, blurb: `FALSE. Bill Gates and Paul Allen were both American.` },
      { id: `co12`, statement: `Peanut butter was first patented by a Canadian.`, correct: true, blurb: `TRUE. Marcellus Gilmore Edson of Montreal patented it in 1884.` },
      { id: `co13`, statement: `Mark Zuckerberg attended university in Canada.`, correct: false, blurb: `FALSE. He attended Harvard.` },
      { id: `co14`, statement: `A Canadian invented the walkie-talkie.`, correct: true, blurb: `TRUE. Donald Hings, a Canadian, built the first one in 1937.` },
      { id: `co15`, statement: `The North Face is a Canadian company.`, correct: false, blurb: `FALSE. The North Face is American, founded in San Francisco.` },
      { id: `co16`, statement: `Elon Musk attended university in Canada.`, correct: true, blurb: `TRUE. He studied at Queen's University in Kingston, Ontario.` },
      { id: `co17`, statement: `Poutine originated in Toronto.`, correct: false, blurb: `FALSE. Poutine originated in rural Quebec in the late 1950s.` },
    ],
  },
  // 7 ─────────────────────────────────────────────────────────────────────
  {
    id: 'grabbag',
    title: 'General Grab-Bag',
    type: 'mc',
    timerSec: 15,
    scoring: { correct: 2, wrong: -1 },
    rules: 'A mix of everything Canadian. Worth more now, +2 for correct! Failure to select an answer will count as a WRONG answer.',
    pointsLabel: '+2 correct · -1 wrong or no answer',
    questions: [
      { id: `g1`, prompt: `In what year did Canada become a country?`,
        options: [{ id: `a`, label: `1776` }, { id: `b`, label: `1812` }, { id: `c`, label: `1867` }, { id: `d`, label: `1931` }],
        correct: `c`, reveal: { blurb: `July 1, 1867, which is why we celebrate Canada Day.` } },
      { id: `g2`, prompt: `What is Canada's national animal?`,
        options: [{ id: `a`, label: `The beaver` }, { id: `b`, label: `The moose` }, { id: `c`, label: `The polar bear` }, { id: `d`, label: `The loon` }],
        correct: `a`, reveal: { blurb: `The beaver, an official symbol of Canada since 1975.` } },
      { id: `g3`, prompt: `How many Canadian teams play in the National Hockey League (NHL)?`,
        options: [{ id: `a`, label: `5` }, { id: `b`, label: `6` }, { id: `c`, label: `7` }, { id: `d`, label: `8` }],
        correct: `c`, reveal: { blurb: `Seven: the Maple Leafs, Canadiens, Senators, Jets, Flames, Oilers, and Canucks.` } },
      { id: `g4`, prompt: `What is Canada's largest province by area?`,
        options: [{ id: `a`, label: `Ontario` }, { id: `b`, label: `Quebec` }, { id: `c`, label: `British Columbia` }, { id: `d`, label: `Alberta` }],
        correct: `b`, reveal: { blurb: `Quebec, larger than Alaska.` } },
      { id: `g5`, prompt: `How many time zones does Canada have?`,
        options: [{ id: `a`, label: `4` }, { id: `b`, label: `5` }, { id: `c`, label: `6` }, { id: `d`, label: `7` }],
        correct: `c`, reveal: { blurb: `Six, from Pacific in the west to Newfoundland in the east.` } },
      { id: `g6`, prompt: `What is Canada's national summer sport?`,
        options: [{ id: `a`, label: `Lacrosse` }, { id: `b`, label: `Soccer` }, { id: `c`, label: `Baseball` }, { id: `d`, label: `Basketball` }],
        correct: `a`, reveal: { blurb: `Lacrosse is the national summer sport; ice hockey is the winter one.` } },
      { id: `g7`, prompt: `How many Canadian teams play in Major League Baseball (MLB)?`,
        options: [{ id: `a`, label: `0` }, { id: `b`, label: `1` }, { id: `c`, label: `2` }, { id: `d`, label: `3` }],
        correct: `b`, reveal: { blurb: `Just one, the Toronto Blue Jays. The Montreal Expos left in 2004.` } },
      { id: `g8`, prompt: `Canada's red-coated national police are nicknamed the ___`,
        options: [{ id: `a`, label: `Mounties` }, { id: `b`, label: `Rangers` }, { id: `c`, label: `Troopers` }, { id: `d`, label: `Redcoats` }],
        correct: `a`, reveal: { blurb: `The Mounties, officially the Royal Canadian Mounted Police.` } },
      { id: `g9`, prompt: `How many countries share a land border with Canada?`,
        options: [{ id: `a`, label: `1` }, { id: `b`, label: `2` }, { id: `c`, label: `3` }, { id: `d`, label: `4` }],
        correct: `b`, reveal: { blurb: `Two: the United States, and Denmark, since a 2022 deal split Hans Island.` } },
      { id: `g10`, prompt: `How many Canadian teams play in the National Basketball Association (NBA)?`,
        options: [{ id: `a`, label: `0` }, { id: `b`, label: `1` }, { id: `c`, label: `2` }, { id: `d`, label: `3` }],
        correct: `b`, reveal: { blurb: `Just one, the Toronto Raptors, NBA champions in 2019.` } },
      { id: `g11`, prompt: `How many provinces and territories does Canada have?`,
        options: [{ id: `a`, label: `10` }, { id: `b`, label: `12` }, { id: `c`, label: `13` }, { id: `d`, label: `15` }],
        correct: `c`, reveal: { blurb: `Thirteen: ten provinces and three territories.` } },
      { id: `g12`, prompt: `How many Canadian teams play in Major League Soccer (MLS)?`,
        options: [{ id: `a`, label: `1` }, { id: `b`, label: `2` }, { id: `c`, label: `3` }, { id: `d`, label: `4` }],
        correct: `c`, reveal: { blurb: `Three: Toronto FC, CF Montreal, and the Vancouver Whitecaps.` } },
      { id: `g13`, prompt: `Where does Canada rank in the world for oil reserves?`,
        options: [{ id: `a`, label: `2nd` }, { id: `b`, label: `3rd` }, { id: `c`, label: `6th` }, { id: `d`, label: `9th` }],
        correct: `b`, reveal: { blurb: `Third, behind Venezuela and Saudi Arabia, thanks to the Alberta oil sands.` } },
    ],
  },
  // 8 ─────────────────────────────────────────────────────────────────────
  {
    id: 'blas',
    title: 'You Should Know This, BLAS!',
    type: 'mixed',
    timerSec: 15,
    multiplier: 4,
    // base values are x1; engine multiplies by `multiplier`. Wrong is a flat -2 (see scoring.js).
    scoring: { correctBase: 1, wrongFlat: -2, drip: { tiers: [2, 1], intervalSec: 10 }, mustAnswer: true },
    rules: 'Your home turf: Canadian tax and finance, worth 4x the points! Mixed formats. Correct +4, and bank clues up to +8. Failure to select an answer will count as a WRONG answer.',
    pointsLabel: '4x scoring · correct +4 (drip +8/+4) · wrong/none -2',
    questions: [
      { id: `b1`, subtype: `mc`, prompt: `What is the current federal GST rate?`,
        options: [{ id: `a`, label: `5%` }, { id: `b`, label: `6%` }, { id: `c`, label: `7%` }, { id: `d`, label: `13%` }],
        correct: `a`, reveal: { blurb: `5%, unchanged since 2008.` } },
      { id: `b2`, subtype: `mc`, prompt: `How many provinces and territories have no provincial sales tax at all?`,
        options: [{ id: `a`, label: `2` }, { id: `b`, label: `4` }, { id: `c`, label: `5` }, { id: `d`, label: `6` }],
        correct: `b`, reveal: { blurb: `Four: Alberta plus the three territories.` } },
      { id: `b3`, subtype: `mc`, prompt: `How many provinces charge HST?`,
        options: [{ id: `a`, label: `3` }, { id: `b`, label: `4` }, { id: `c`, label: `5` }, { id: `d`, label: `6` }],
        correct: `c`, reveal: { blurb: `Five: Ontario, New Brunswick, Newfoundland and Labrador, Nova Scotia, and Prince Edward Island.` } },
      { id: `b4`, subtype: `mc`, prompt: `What is Ontario's HST rate?`,
        options: [{ id: `a`, label: `5%` }, { id: `b`, label: `8%` }, { id: `c`, label: `13%` }, { id: `d`, label: `0%` }],
        correct: `c`, reveal: { blurb: `13%, which is 5% federal plus 8% provincial.` } },
      { id: `b5`, subtype: `tf`, statement: `Nova Scotia's HST rate is 15%.`,
        correct: false, reveal: { blurb: `FALSE. Nova Scotia lowered its HST to 14% on April 1, 2025.` } },
      { id: `b6`, subtype: `mc`, prompt: `A corporation with a January 31 year-end must file its T2 return by which date?`,
        options: [{ id: `a`, label: `April 30` }, { id: `b`, label: `June 30` }, { id: `c`, label: `July 31` }, { id: `d`, label: `January 31` }],
        correct: `c`, reveal: { blurb: `Six months after the year-end, so July 31.` } },
      { id: `b7`, subtype: `mc`, prompt: `A company with annual HST filing and a December 31 year-end must file its HST return by which date?`,
        options: [{ id: `a`, label: `April 30` }, { id: `b`, label: `June 15` }, { id: `c`, label: `June 30` }, { id: `d`, label: `March 31` }],
        correct: `d`, reveal: { blurb: `Three months after the fiscal year-end, so March 31.` } },
      { id: `b8`, subtype: `tf`, statement: `A business must register for GST/HST once its annual revenue exceeds $50,000.`,
        correct: false, reveal: { blurb: `FALSE. The small-supplier threshold is $30,000, not $50,000.` } },
      { id: `b9`, subtype: `mc`, prompt: `Where does Nick live?`,
        options: [{ id: `a`, label: `Toronto` }, { id: `b`, label: `Mississauga` }, { id: `c`, label: `North York` }, { id: `d`, label: `Richmond Hill` }],
        correct: `c`, reveal: { blurb: `North York.` } },
      { id: `b10`, subtype: `mc`, prompt: `Ayaz went to university in which city?`,
        options: [{ id: `a`, label: `Toronto` }, { id: `b`, label: `Ottawa` }, { id: `c`, label: `Waterloo` }, { id: `d`, label: `Kitchener` }],
        correct: `c`, reveal: { blurb: `Waterloo.` } },
      { id: `b11`, subtype: `tf`, statement: `Boris is a CPA.`,
        correct: false, reveal: { blurb: `FALSE.` } },
      { id: `b12`, subtype: `bank-drip`,
        clues: [`I am the biggest bank in Canada by assets.`, `My brand colour is blue, and my logo has a globe.`],
        options: [{ id: `a`, label: `RBC` }, { id: `b`, label: `BMO` }, { id: `c`, label: `Scotiabank` }, { id: `d`, label: `TD` }, { id: `e`, label: `CIBC` }],
        correct: `a`, reveal: { blurb: `RBC, the Royal Bank of Canada.` } },
    ],
  },
]

// FINALE ────────────────────────────────────────────────────────────────────
export const FINALE = {
  id: 'wager',
  title: 'The Final Wager',
  type: 'wager',
  timerSec: 30,
  category: 'The Meaning of Canada',
  rules: 'Bet any portion of your (hidden) points with the slider, THEN see the question. Right = you gain your wager. Wrong = you lose it. This decides everything.',
  prompt: 'What does the word "Canada" actually mean?',
  options: [
    { id: 'a', label: 'The Great White North' },
    { id: 'b', label: 'Village or Settlement' },
    { id: 'c', label: 'Land of Many Rivers' },
    { id: 'd', label: 'New France' },
  ],
  correct: 'b',
  reveal: { blurb: 'It comes from the Iroquoian word "kanata," meaning village or settlement.' },
}

export const GLOBAL = {
  eventTitle: 'BLAS Canada Day Trivia',
  brandTeal: '#128A6B',   // placeholder, replaced with exact BLAS hex from logo files
  flagRed: '#D80621',
}
